### ISSUE TITLE
Bug Module Table 

### ISSUE THREAD

**Issue by kewelinho** [Innoto/cogumelo#166]
Cuando defines una tabla es obligatorio definir unas tabs sino peta la tabla.

Ejemplo : 
$tabla->setTabs('name', array( '*'=> 'Todos' ), '*');

Si no estableces una tab por defecto la tabla suelta varios errores. La propia biblioteca debería detectar que si no hay tabs definidos, lista todo y oculta el selector de tab principal.

**Comment by pablinhob** [comment]
DONE!
