### ISSUE TITLE
Includes en tpl con ruta relativa

### ISSUE THREAD

**Issue by pablinhob** [Innoto/cogumelo#173]
Estanse incluindo os tpl coa ruta absoluta dende os modulos. Conseguir que smarty inclua tpls dende o propio template  con rutas relativas.

**Comment by jmpmato** [comment]
Pueden cargarse TPLs de modulos usando nombremodulo///fichero.tpl
Se asume que la ruta dentro del módulo es classes/view/templates/ dando como resultando nombremodulo/classes/view/templates/fichero.tpl

Funciona dentro de TPLs (include o similar) y con los comandos de Smarty desde PHP.
